In [41]:
import numpy as np

# Question 1

a = np.arange(9)
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Question 2

a = np.arange(10)
for i in range(len(a)):
    a[i]=-1 if(a[i]%2==1) else a[i]
print(a)

In [22]:
# Question 3

#x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
#y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

x = np.random.randint(0,100,10)
y = np.random.randint(0,100,10)

print(np.where(x>y))
print(np.where(x==y))

(array([0, 1, 2, 4, 7, 8, 9]),)
(array([], dtype=int64),)


In [18]:
# Question 4

a = np.arange(100).reshape(5,-1)
print(a[:,:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [20]:
# Additional 1

print(np.random.randint(30,41,10))

[31 33 31 30 32 31 36 37 39 30]


In [37]:
# Additonal 2

a = np.array([(1,2,3),(4,5,6),(7,8,10)])
b = a[::-1,:]
c = a+b
e = a-b
print("A+B:",c)
print("A-B:",e)
print("Sum of Matrix A:",np.sum(a))
print("Sum of Columns of Matrix B:", np.sum(b,axis=0))
print("Sum of rows of Matrix C:", np.sum(c,axis=1))
d = a*b
print("A*B:",d)
e = np.sort(c, axis=1)
print("Sort C:",e)
print("Transpose E:",e.transpose())

A+B: [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
A-B: [[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]
Sum of Matrix A: 46
Sum of Columns of Matrix B: [12 15 19]
Sum of rows of Matrix C: [31 30 31]
A*B: [[ 7 16 30]
 [16 25 36]
 [ 7 16 30]]
Sort C: [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
Transpose E: [[ 8  8  8]
 [10 10 10]
 [13 12 13]]
